# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# Recovery behaviors are defined in robot folders

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 1.0
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 10.0
controller_patience: 5.0

DWAPlannerROS:
  acc_lim_x: 0.3
  acc_lim_y: 0.3
  acc_lim_th: 0.4
  
  max_trans_vel: 0.3
  min_trans_vel: 0.1
  max_vel_x: 0.3
  min_vel_x: 0.0 # disable to move backward
  max_vel_y: 0.3
  min_vel_y: -0.3
  max_rot_vel: 0.8
  min_rot_vel: 0.1
  
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  
  sim_time: 1.7
  sim_granularity: 0.025
  
  vx_samples: 6
  vy_samples: 6
  vth_samples: 12
